### ISSUE TITLE
Font size and "Pts" add on Challenge&Rewards page

### ISSUE THREAD

**Issue by emmanuelaldeguer** [okp4/nemeton-web#20]
Font size is much too high and I suggest to add "Pts" after figures to avoid any confusion.

**Comment by fredericvilcot** [comment]
@emmanuelaldeguer 
Joakim a effectué une baisse de la taille des polices et ajouté "points" comme légende des tâches.
Pourrais-tu tester sur le staging https://nemeton.staging.okp4.network/ et nous faire un retour?

**Comment by fredericvilcot** [comment]
@emmanuelaldeguer 
Joakim a effectué une baisse de la taille des polices et ajouté "points" comme légende des tâches.
Pourrais-tu tester sur le staging https://nemeton.staging.okp4.network/ et nous faire un retour?

**Comment by emmanuelaldeguer** [comment]
> @emmanuelaldeguer Joakim a effectué une baisse de la taille des polices et ajouté "points" comme légende des tâches. Pourrais-tu tester sur le staging https://nemeton.staging.okp4.network/ et nous faire un retour?

OK EXCEPT FOR : 
Home Challenge and Rewards details. Fonts should be reduced.
And white lines let think that it is a sum I would deleted them.

Bold chapters numbers in TERMS

**Comment by ccamel** [comment]
@fredericvilcot in english please. issue is public. thx.

**Comment by emmanuelaldeguer** [comment]
> > @fredericvilcot in english please. issue is public. thx.
> 
> For sure, I don't even know why I wrote in French...
> 
> @emmanuelaldeguer I'll made the changes myself.

Thx !

**Comment by fredericvilcot** [comment]
@emmanuelaldeguer 
Changes are deployed in staging, let me know if it fits your remarks.
