### ISSUE TITLE
Add link to tutorials in Builders Program FAQ

### ISSUE THREAD

**Issue by ccamel** [okp4/nemeton-web#233]
## Issue

The [FAQ page](https://nemeton.okp4.network/validators/faq#faq) of the Builders Program omits any reference to the tutorials provided at <https://docs.okp4.network/tutorials/overview>. Moreover, the inclusion of the nodes and validators documentation link is irrelevant in this context and should be removed.

<img width="1552" alt="image" src="https://github.com/okp4/nemeton-web/assets/9574336/8d6cf00f-a5ec-4ead-9e69-fafe4cd639f7">

---

FYI @antho31

**Comment by houssemmimoun27** [comment]
@ccamel 
The nodes and validators documentation link should be only removed from the builders program FAQ ?

**Comment by ccamel** [comment]
> @ccamel 
> The nodes and validators documentation link should be only removed from the builders program FAQ ?

Yes. Due to their distinct target audiences and different thematic focuses, the two programs also come with varying documentation.
